spring.application.name=booking-service
server.port=8083

spring.datasource.url=jdbc:h2:mem:bookingdb;DB_CLOSE_DELAY=-1;MODE=LEGACY
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

user.service.url=http://user-service:8081/api/users
court.service.url=http://court-service:8082/api/courts
